import React from 'react';

interface AppShellProps {
  children: React.ReactNode;
  logo?: React.ReactNode;
  footer?: React.ReactNode;
}

export const AppShell: React.FC<AppShellProps> = ({
  children,
  logo,
  footer,
}) => {
  return (
    <div className="flex justify-center items-start p-5 min-h-screen bg-surface">
      <div
        id="app"
        className="flex flex-col w-[800px] min-w-[500px] bg-primary-container rounded-lg overflow-hidden shadow-xl"
      >
        {logo && (
          <div
            id="logo-container"
            className="pt-6 px-6 flex justify-center items-center"
          >
            {logo}
          </div>
        )}

        <main
          id="content"
          className="m-6 p-4 bg-surface text-on-surface rounded-md"
        >
          {children}
        </main>

        <footer
          id="footer"
          className="px-6 pb-6 text-center text-xs text-on-surface-variant opacity-80 leading-relaxed"
        >
          <div id="datetime">{new Date().toLocaleString()}</div>
          <div>Generated by AmiaBot</div>
          <div>Designed by Parallel SEKAI</div>
          {footer}
        </footer>
      </div>
    </div>
  );
};
